import Head from "next/head";
import Image from "next/image";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Register from "./register";
import Hero from "../components/Hero";
import { useRouter } from "next/router";
import { useMoralis } from "react-moralis";

export default function Home() {
  return (
    <>
      <Head>
        <title>Insurechain</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/public/favicon.png" />
      </Head>
      <Navbar />
      <Hero />
    </>
  );
}
